export default {
  registerHeading: "Create your account",
  or: "Or",
  toLogin: "Sign in to your account",
  email_address: "Email address",
  password: "Password",
  confirm_password: "Confirm password",
  first_name: "First name",
  last_name: "Last name",
  phone_number: "Phone number",
  address: "Address",
  zip: "ZIP",
  country: "Country",
  note: "Note",
  registerButton: "Create account",
  loginHeading: "Log in to your account",
  toRegister: "Create new account",
  loginButton: "Log in",
  search: "Search...",
  previousButton: "Previous",
  nextButton: "Next",
  first_page: "You are on first page!",
  save_button: "Save",
  delete_button: "Delete",
  confirm_delete: "Are you sure you want to delete this user?",
  delete_confirmation: "User was successfully deleted",
  delete_error: "There was an error while deleting user",
  edit_confirmation: "User was successfully edited",
  edit_error: "There was an error while editing user",
  contacts_error: "There was an error while fetching contacts",
  logout_success: "You have been logged out successfully",
  logout_error: "There was an error while logging out",
  fetch_user_error: "There was an error while fetching users",
  login_no_success: "Incorrect login details",
  login_success: "You have been logged in successfully"
};
