export default {
  registerHeading: "Vytvoriť si účet",
  or: "Alebo",
  toLogin: "Prihlásiť sa",
  email_address: "Email",
  password: "Heslo",
  confirm_password: "Potvrdiť heslo",
  first_name: "Meno",
  last_name: "Priezvisko",
  phone_number: "Telefónne číslo",
  address: "Adresa",
  zip: "PSČ",
  country: "Krajina",
  note: "Poznámka",
  registerButton: "Registrovať sa",
  loginHeading: "Prihlásenie",
  toRegister: "Vytvoriť nový účet",
  loginButton: "Prihlásiť sa",
  search: "Hľadať...",
  previousButton: "Predošlá strana",
  nextButton: "Ďaľšia strana",
  first_page: "Ste na prvej strane!",
  save_button: "Uložiť",
  delete_button: "Vymazať",
  confirm_delete: "Ste si istý že chcete vymazať tohoto používateľa?",
  delete_confirmation: "Používateľ bol úspešne vymazaný",
  delete_error: "Pri snahe vymazať používateľa sa vyskytla chyba",
  edit_confirmation: "Používateľ bol úspešne editovaný",
  edit_error: "Pri snahe editovať používateľa sa vyskytla chyba",
  contacts_error: "Pri snahe obnoviť kontakty sa vyskytla chyba",
  logout_success: "Odhlásenie prebehlo úspešne",
  logout_error: "Pri snahe odhlásiť sa sa vyskytla chyba",
  fetch_user_error: "Pri snahe obnoviť používateľov sa vyskytla chyba",
  login_no_success: "Nesprávne prihlasovacie údaje",
  login_success: "Prihlásenie prebehlo úspešne"
};
